#!/usr/bin/perl

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $OPENTRACKERDIR = "/root/opentracker";
my $SCREENCMD = "/usr/bin/screen";
my $OPENTRACKEREXE = "./opentracker -f ./opentracker.conf";

# No changes below here...

my $exists = "";

# Set ENV vars
$ENV{'TERM'} = "xterm-256color";

my $running=`ps ax|grep opentracker|grep -v grep|grep -v startopentracker`;

# check if Opentracker process is running
if ($running ne "")
{
	print ("Startupscript already running...\n");
	exit (0);
}

while (-1)
{
	chdir $OPENTRACKERDIR;
	# check if Opentracker process is running
	$running=`ps ax|grep opentracker|grep -v grep|grep -v startopentracker`;
	if ($running eq "")
	{
		print "Opentracker not running\n";
		# See if they want Opentracker started
		if (! -f "$OPENTRACKERDIR/nostart")
		{
			# The Log Entry
			my $datestring = localtime();
			my $TIME="Opentracker Down, Restarting: $datestring";
			open(OUTF, ">>$OPENTRACKERDIR/OpentrackerServerScreen.log") || die "Unable to open $OPENTRACKERDIR/OpentrackerServerScreen.log for appending";
			print (OUTF "$TIME\n");
			close($OUTF);
			chdir $OPENTRACKERDIR;
			print "Starting screen process\n";
			system("$SCREENCMD -fa -S Opentracker -d -U -m $OPENTRACKEREXE");
		}
	}
	# Sleep for 5 minutes before checking again
	sleep(300);
}
exit(0);
